name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

env:
    GH_TOKEN: ${{ github.token }}

permissions:
  contents: write
  discussions: write

on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
      - run: git archive -o latest.zip HEAD
      - run: gh release upload Latest latest.zip --clobber
      # - uses: softprops/action-gh-release@v1
      #   with:
      #     files: latest.zip
# extra c omment