name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - run: ls ${{ github.workspace }}
      # - run: git archive -o latest.zip HEAD
      # - run: gh release upload Latest latest.zip --clobber
      # - run: rm latest.zip
#