name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

env:
    GH_TOKEN: ${{ github.token }}

on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - run: |
            git archive -o latest.zip HEAD
            ls ${{ github.workspace }}
            gh release upload Latest latest.zip --clobber
# extra c omment